package com.example.templatefinal.DomainModels;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChiTietSp generated by hbm2java
 */
@Entity
@Table(name = "ChiTietSP",
        schema = "dbo",
        catalog = "FINALASS_FPOLYSHOP_FA22_SOF205__SOF2041"
)
public class ChiTietSp implements java.io.Serializable {

    @Column(name="Id", unique=true, nullable=false, length=36)
    @Id
    private UUID id;
    @ManyToOne(fetch=FetchType.EAGER )
    @JoinColumn(name="IdDongSP")
    private DongSp dongSp;
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IdMauSac")
    private MauSac mauSac;
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IdNsx")
    private Nsx nsx;
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IdSP")
    private SanPham sanPham;
    @Column(name="NamBH")
    private Integer namBh;
    @Column(name="MoTa")
    private String moTa;
    @Column(name="SoLuongTon")
    private Integer soLuongTon;
    @Column(name="GiaNhap", precision=20, scale=0)
    private BigDecimal giaNhap;
    @Column(name="GiaBan", precision=20, scale=0)
    private BigDecimal giaBan;

    public ChiTietSp() {
    }


    public ChiTietSp(UUID id) {
        this.id = id;
    }
    public ChiTietSp(UUID id, DongSp dongSp, MauSac mauSac, Nsx nsx, SanPham sanPham, Integer namBh, String moTa, Integer soLuongTon, BigDecimal giaNhap, BigDecimal giaBan) {
        this.id = id;
        this.dongSp = dongSp;
        this.mauSac = mauSac;
        this.nsx = nsx;
        this.sanPham = sanPham;
        this.namBh = namBh;
        this.moTa = moTa;
        this.soLuongTon = soLuongTon;
        this.giaNhap = giaNhap;
        this.giaBan = giaBan;
    }




    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public DongSp getDongSp() {
        return this.dongSp;
    }

    public void setDongSp(DongSp dongSp) {
        this.dongSp = dongSp;
    }

    public MauSac getMauSac() {
        return this.mauSac;
    }

    public void setMauSac(MauSac mauSac) {
        this.mauSac = mauSac;
    }

    public Nsx getNsx() {
        return this.nsx;
    }

    public void setNsx(Nsx nsx) {
        this.nsx = nsx;
    }

    public SanPham getSanPham() {
        return this.sanPham;
    }

    public void setSanPham(SanPham sanPham) {
        this.sanPham = sanPham;
    }


    public Integer getNamBh() {
        return this.namBh;
    }

    public void setNamBh(Integer namBh) {
        this.namBh = namBh;
    }


    public String getMoTa() {
        return this.moTa;
    }

    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }


    public Integer getSoLuongTon() {
        return this.soLuongTon;
    }

    public void setSoLuongTon(Integer soLuongTon) {
        this.soLuongTon = soLuongTon;
    }


    public BigDecimal getGiaNhap() {
        return this.giaNhap;
    }

    public void setGiaNhap(BigDecimal giaNhap) {
        this.giaNhap = giaNhap;
    }


    public BigDecimal getGiaBan() {
        return this.giaBan;
    }

    public void setGiaBan(BigDecimal giaBan) {
        this.giaBan = giaBan;
    }

    @Override
    public String toString() {
        return sanPham.getTen();
    }
}
