package com.example.templatefinal.DomainModels;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import javax.persistence.*;

/**
 * SanPham generated by hbm2java
 */
@Entity
@Table(name = "SanPham",
        schema = "dbo",
        catalog = "FINALASS_FPOLYSHOP_FA22_SOF205__SOF2041",
        uniqueConstraints = @UniqueConstraint(columnNames = "Ma")
)
public class SanPham implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private UUID id;
    @Column(name = "Ma", unique = true, length = 20)
    private String ma;
    @Column(name = "Ten")
    private String ten;
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "sanPham" ,cascade = CascadeType.ALL)
    private Set<ChiTietSp> chiTietSps;

    public SanPham() {
    }

    public SanPham(UUID id) {
        this.id = id;
    }

    public SanPham(UUID id, String ma, String ten, Set<ChiTietSp> chiTietSps) {
        this.id = id;
        this.ma = ma;
        this.ten = ten;
        this.chiTietSps = chiTietSps;
    }

    public SanPham(String ma, String ten) {
        this.ma = ma;
        this.ten = ten;
    }

    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getMa() {
        return this.ma;
    }

    public void setMa(String ma) {
        this.ma = ma;
    }

    public String getTen() {
        return this.ten;
    }

    public void setTen(String ten) {
        this.ten = ten;
    }

    public Set<ChiTietSp> getChiTietSps() {
        return this.chiTietSps;
    }

    public void setChiTietSps(Set<ChiTietSp> chiTietSps) {
        this.chiTietSps = chiTietSps;
    }

    @Override
    public String toString() {
        return  ten ;
    }
}
